name = input("enter the characters name: ")
age = input("enter the characters age: ")
species = input("enter the characters species: ")
world = input("enter the characters world")
hobby = input("enter the characters hobby")
print("name: " + name)
print("age: " + age + "years old")
print("species" + species)
print("world: " + world)
print("hobby: " + hobby)